### ISSUE TITLE
Build error?

### ISSUE THREAD

**Issue by kenlee-sal** [JReming85/rustdesk-kasm-image#4]
I tried to build my own image but somehow got this error:

146.1 Reading package lists...
148.6 Building dependency tree...
149.1 Reading state information...
149.4 Some packages could not be installed. This may mean that you have
149.4 requested an impossible situation or if you are using the unstable
149.4 distribution that some required packages have not yet been created
149.4 or been moved out of Incoming.
149.4 The following information may help to resolve the situation:
149.4
149.4 The following packages have unmet dependencies:
149.6  rustdesk:amd64 : Depends: libgtk-3-0:amd64 but it is not installable
149.6                   Depends: libxcb-randr0:amd64 but it is not installable
149.6                   Depends: libxdo3:amd64 but it is not installable
149.6                   Depends: libxfixes3:amd64 but it is not installable
149.6                   Depends: libxcb-shape0:amd64 but it is not installable
149.6                   Depends: libxcb-xfixes0:amd64 but it is not installable
149.6                   Depends: libasound2:amd64 but it is not installable
149.6                   Depends: libsystemd0:amd64 but it is not installable
149.6                   Depends: libva-drm2:amd64 but it is not installable
149.6                   Depends: libva-x11-2:amd64 but it is not installable
149.7                   Depends: libvdpau1:amd64 but it is not installable
149.7                   Depends: libgstreamer-plugins-base1.0-0:amd64 but it is not installable
149.7                   Depends: libpam0g:amd64 but it is not installable
149.7                   Depends: libappindicator3-1:amd64 but it is not installable
149.7                   Depends: gstreamer1.0-pipewire:amd64 but it is not installable
149.7 E: Unable to correct problems, you have held broken packages.
------
Dockerfile:11
--------------------
  10 |
  11 | >>> RUN  TEMP_DEB="$(mktemp).deb" \
  12 | >>>         && add-apt-repository ppa:pipewire-debian/pipewire-upstream \
  13 | >>>         && apt-get -f install libxcb-randr0 libxdo3 gstreamer1.0-pipewire -y\
  14 | >>>         && LATESTURL="$(curl -f -L https://github.com/rustdesk/rustdesk/releases/latest | grep -Eo 'https://[a-zA-Z0-9#~.*,/!?=+&_%:-]*-x86_64.deb')" \
  15 | >>>         && wget -O $TEMP_DEB $LATESTURL \
  16 | >>>         && apt install -f $TEMP_DEB -y\
  17 | >>>         && rm -f "$TEMP_DEB" \
  18 | >>>         && wget -O "$HOME/Desktop/rustdesk.desktop" https://gitlab.com/jeremyrem/rustdesk-kasm-image/-/raw/main/rustdesk.desktop \
  19 | >>>         && chmod +x $HOME/Desktop/rustdesk.desktop  \
  20 | >>>         && chown 1000:1000 $HOME/Desktop/rustdesk.desktop
  21 |
--------------------
ERROR: failed to solve: process "/bin/sh -c TEMP_DEB=\"$(mktemp).deb\"         && add-apt-repository ppa:pipewire-debian/pipewire-upstream         && apt-get -f install libxcb-randr0 libxdo3 gstreamer1.0-pipewire -y        && LATESTURL=\"$(curl -f -L https://github.com/rustdesk/rustdesk/releases/latest | grep -Eo 'https://[a-zA-Z0-9#~.*,/!?=+&_%:-]*-x86_64.deb')\"         && wget -O $TEMP_DEB $LATESTURL         && apt install -f $TEMP_DEB -y        && rm -f \"$TEMP_DEB\"         && wget -O \"$HOME/Desktop/rustdesk.desktop\" https://gitlab.com/jeremyrem/rustdesk-kasm-image/-/raw/main/rustdesk.desktop         && chmod +x $HOME/Desktop/rustdesk.desktop          && chown 1000:1000 $HOME/Desktop/rustdesk.desktop" did not complete successfully: exit code: 100

**Comment by kenlee-sal** [comment]
oh it seems that running this on ARM PC will result in this error

**Comment by JReming85** [comment]
Yes, just edit the build file to grab the arm version instead of the x86_64
file
